import { describe, expect, it } from 'vitest';
import { buildApp } from '../src/app.js';

describe('HTTP foundation', () => {
  it('returns health status', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/health'}); expect(response.statusCode).toBe(200); expect(response.json()).toMatchObject({status:'ok'}); await app.close(); });
  it('returns a readiness response', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/ready'}); expect([200,503]).toContain(response.statusCode); expect(response.json()).toHaveProperty('status'); await app.close(); });
  it('serves API metadata and OpenAPI', async () => { const app=buildApp(); const metadata=await app.inject({method:'GET',url:'/api/v1'}); const openapi=await app.inject({method:'GET',url:'/openapi.json'}); expect(metadata.statusCode).toBe(200); expect(metadata.json()).toHaveProperty('version'); expect(openapi.statusCode).toBe(200); expect(openapi.json()).toHaveProperty('paths'); await app.close(); });
  it('validates geography route identifiers', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/public/geography/wilayas/not-a-number/dairas'}); expect(response.statusCode).toBe(400); await app.close(); });
  it('rejects malformed login requests', async () => { const app=buildApp(); const response=await app.inject({method:'POST',url:'/api/v1/auth/login',payload:{username:'x',password:'short'}}); expect(response.statusCode).toBe(400); await app.close(); });
  it('protects administration routes', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/seasons'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('rejects logout without authentication', async () => { const app=buildApp(); const response=await app.inject({method:'POST',url:'/api/v1/auth/logout'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('rejects session lookup without authentication', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/auth/me'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('protects administrative reports', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/reports/summary'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('protects report status breakdown', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/reports/status-breakdown'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('allows the configured frontend origin', async () => { const app=buildApp(); const response=await app.inject({method:'OPTIONS',url:'/health',headers:{origin:'http://localhost:5173','access-control-request-method':'GET'}}); expect(response.headers['access-control-allow-origin']).toBe('http://localhost:5173'); await app.close(); });
  it('does not expose verification results to browser caches', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/public/licenses/verify/invalid-reference-value-12345678901234567890'}); expect(response.headers['cache-control']).toBe('no-store'); expect(response.statusCode).toBe(401); await app.close(); });
  it('rejects spectator license verification', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/verify/invalid-reference-value-12345678901234567890'}); expect(response.statusCode).toBe(401); expect(response.json()).not.toHaveProperty('licenseId'); await app.close(); });
  it('rejects audit detail access without authentication', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/audit/00000000-0000-0000-0000-000000000000'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('validates public season identifiers', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/public/seasons/not-a-uuid'}); expect(response.statusCode).toBe(400); await app.close(); });
  it('protects announcement administration', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/announcements'}); expect(response.statusCode).toBe(401); await app.close(); });
  it('protects enrollment card issuance', async () => { const app=buildApp(); const response=await app.inject({method:'GET',url:'/api/v1/admin/cards'}); expect(response.statusCode).toBe(401); await app.close(); });
});
