import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../infrastructure/db.js';
import { assertTransition } from '../domain/lifecycle.js';
import { AuthenticatedRequest, canAccessResource, hasPermission, hasRole, recordAccessDenied, requireAuth, requirePolicy, scopeCondition, scopeKind } from '../http/auth-guard.js';
import { createVerificationReference, hashVerificationReference } from '../services/verification.js';
import { encodePassword } from '../services/auth.js';

const seasonInput = z.object({ name: z.string().min(2).max(200), startDate: z.coerce.date(), endDate: z.coerce.date() }).refine((v) => v.endDate >= v.startDate, 'endDate must be after startDate');
const organizationInput = z.object({ name: z.string().min(2).max(200), code: z.string().max(50).optional() });
const participantInput = z.object({ institutionId: z.string().uuid(), givenName: z.string().min(1).max(100), familyName: z.string().min(1).max(100), dateOfBirth: z.coerce.date().optional() });
const competitionInput = z.object({ seasonId: z.string().uuid(), name: z.string().min(2).max(200), startDate: z.coerce.date().optional(), endDate: z.coerce.date().optional(), sportKind: z.enum(['INDIVIDUAL','TEAM']).optional(), ageCategory: z.enum(['U11','U13','U15','U17','U19','OPEN']).optional(), genderCategory: z.enum(['MALE','FEMALE','MIXED']).optional(), rulesText: z.string().max(2000).optional() });
const licenseInput = z.object({
  participantId: z.string().uuid(),
  expiresAt: z.coerce.date().optional(),
  licenseKind: z.enum(['STUDENT', 'COACH', 'OFFICIAL']).optional(),
  discipline: z.string().min(2).max(80).optional(),
  sportKind: z.enum(['INDIVIDUAL', 'TEAM']).optional(),
  ageCategory: z.enum(['U11', 'U13', 'U15', 'U17', 'U19', 'OPEN']).optional(),
  genderCategory: z.enum(['MALE', 'FEMALE', 'MIXED']).optional()
});
const resultInput = z.object({ participantId: z.string().uuid().optional(), resultData: z.record(z.unknown()) });

async function audit(actorUserId: string, action: string, entityType: string, entityId: string, metadata: object = {}) { await pool.query('INSERT INTO audit_logs (actor_user_id, action, entity_type, entity_id, result_status, metadata) VALUES ($1,$2,$3,$4,$5,$6)', [actorUserId, action, entityType, entityId, 'SUCCESS', metadata]); }
async function filterScopedRows(request: AuthenticatedRequest, resource: 'organization'|'institution'|'participant'|'license'|'result', rows: any[]): Promise<any[]> {
  if (scopeKind(request) === 'national') return rows;
  const ids = rows.map((row) => row.id).filter((id): id is string => typeof id === 'string'); if (!ids.length) return [];
  const tables: Record<typeof resource, string> = { organization: 'organizations', institution: 'educational_institutions', participant: 'participants', license: 'sports_licenses', result: 'results' };
  const { sql, values } = scopeCondition(request, resource, 'r', 2);
  const allowed = await pool.query(`SELECT r.id FROM ${tables[resource]} r WHERE r.id=ANY($1::uuid[]) AND ${sql}`, [ids, ...values]);
  const allowedIds = new Set(allowed.rows.map((row) => row.id)); return rows.filter((row) => allowedIds.has(row.id));
}

export async function registerAdminRoutes(app: FastifyInstance) {
  app.addHook('preHandler', async (request, reply) => {
    const req = request as AuthenticatedRequest; const path = request.url.split('?')[0];
    if (!path.startsWith('/api/v1/admin')) return;
    if (!requireAuth(req, reply)) return;
    if (path.endsWith('/me/permissions')) return;
    const nationalOnly = /\/users(?:\/|$)|\/roles(?:\/|$)|\/permissions(?:\/|$)|\/audit(?:\/|$)|\/reports(?:\/|$)|\/licenses\/sync-expiry|\/announcements(?:\/|$)/.test(path);
    if (nationalOnly) { if (!hasRole(req, ['SYSTEM_ADMINISTRATOR', 'NATIONAL_ADMINISTRATOR'])) { await recordAccessDenied(req, 'NATIONAL_SCOPE_DENIED'); void reply.code(403).send({ error: 'forbidden' }); } return; }
    if (/\/seasons(?:\/|$)|\/competitions(?:\/|$)/.test(path)) {
      if (request.method !== 'GET' && scopeKind(req) !== 'national') { await recordAccessDenied(req, 'NATIONAL_SCOPE_DENIED', 'GLOBAL_RESOURCE'); void reply.code(403).send({ error: 'forbidden' }); }
      return;
    }
    if (/\/entries(?:\/|$)/.test(path)) { await requirePolicy(req, reply, { resource: 'participant' }); return; }
    let resource: 'organization'|'institution'|'participant'|'license'|'result'|undefined;
    if (/\/organizations(?:\/|$)/.test(path)) resource = 'organization';
    else if (/\/(?:educational_)?institutions(?:\/|$)/.test(path)) resource = 'institution';
    else if (/\/participants(?:\/|$)/.test(path)) resource = 'participant';
    else if (/\/licenses(?:\/|$)/.test(path)) resource = 'license';
    else if (/\/results(?:\/|$)/.test(path)) resource = 'result';
    if (!resource) { if (path.endsWith('/lookups')) { await requirePolicy(req, reply, { resource: 'institution' }); } return; }
    if (!(await requirePolicy(req, reply, { resource }))) return;
    const match = path.match(/\/([0-9a-f-]{36})(?:\/|$)/i);
    if (match && !(await canAccessResource(req, resource, match[1]))) { await recordAccessDenied(req, 'RESOURCE_SCOPE_DENIED', resource.toUpperCase()); void reply.code(403).send({ error: 'forbidden' }); return; }
    const body = (request.body ?? {}) as Record<string, unknown>; const relatedId = resource === 'institution' ? body.organizationId : resource === 'participant' ? body.institutionId : resource === 'license' ? body.participantId : undefined;
    if (typeof relatedId === 'string') { const relatedResource = resource === 'institution' ? 'organization' : resource === 'participant' ? 'institution' : 'participant'; if (!(await canAccessResource(req, relatedResource, relatedId))) { await recordAccessDenied(req, 'RELATED_RESOURCE_SCOPE_DENIED', relatedResource.toUpperCase()); void reply.code(403).send({ error: 'forbidden' }); return; } }
  });
  app.addHook('onSend', async (request, _reply, payload) => {
    if (request.method !== 'GET' || !request.url.startsWith('/api/v1/admin/')) return payload;
    const req = request as AuthenticatedRequest; if (!req.auth || scopeKind(req) === 'national') return payload;
    const path = request.url.split('?')[0]; const resource = /\/organizations(?:\/|$)/.test(path) ? 'organization' : /\/(?:educational_)?institutions(?:\/|$)/.test(path) ? 'institution' : /\/participants(?:\/|$)/.test(path) ? 'participant' : /\/licenses(?:\/|$)/.test(path) ? 'license' : /\/results(?:\/|$)/.test(path) ? 'result' : undefined;
    const raw = Buffer.isBuffer(payload) ? payload.toString('utf8') : typeof payload === 'string' ? payload : JSON.stringify(payload); let body: any; try { body = JSON.parse(raw); } catch { return payload; }
    if (path.endsWith('/lookups') && body?.data) { body.data.participants = await filterScopedRows(req, 'participant', body.data.participants ?? []); body.data.organizations = await filterScopedRows(req, 'organization', body.data.organizations ?? []); return JSON.stringify(body); }
    if (!resource || !Array.isArray(body?.data)) return payload;
    body.data = await filterScopedRows(req, resource, body.data); return JSON.stringify(body);
  });
  app.post('/api/v1/admin/users', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const parsed=z.object({username:z.string().min(3).max(100),email:z.string().email().optional(),displayName:z.string().min(2).max(200),password:z.string().min(12).max(200),roleIds:z.array(z.string().uuid()).min(1).max(10)}).safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error',details:parsed.error.flatten()}); const roles=await pool.query('SELECT id FROM roles WHERE id=ANY($1::uuid[])',[parsed.data.roleIds]); if(roles.rowCount!==parsed.data.roleIds.length)return reply.code(400).send({error:'role_not_found'}); const client=await pool.connect(); try{await client.query('BEGIN'); const user=await client.query('INSERT INTO users(username,email,display_name,password_hash) VALUES($1,$2,$3,$4) RETURNING id,username,email,display_name,status',[parsed.data.username,parsed.data.email??null,parsed.data.displayName,encodePassword(parsed.data.password)]); for(const roleId of parsed.data.roleIds)await client.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2)',[user.rows[0].id,roleId]); await client.query('COMMIT'); await audit(req.auth!.userId,'CREATE','USER',user.rows[0].id,{roleIds:parsed.data.roleIds}); return reply.code(201).send({data:user.rows[0]}); }catch(error){await client.query('ROLLBACK'); if((error as {code?:string}).code==='23505')return reply.code(409).send({error:'username_or_email_exists'}); throw error;}finally{client.release()} });
  app.post('/api/v1/admin/users/:id/status', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({status:z.enum(['ACTIVE','SUSPENDED','DISABLED'])}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); if(id.data===req.auth!.userId&&parsed.data.status!=='ACTIVE')return reply.code(409).send({error:'cannot_disable_current_user'}); const result=await pool.query('UPDATE users SET status=$1,updated_at=now() WHERE id=$2 RETURNING id,username,status',[parsed.data.status,id.data]); if(!result.rowCount)return reply.code(404).send({error:'user_not_found'}); await audit(req.auth!.userId,'UPDATE_STATUS','USER',id.data,{status:parsed.data.status}); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/me/permissions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; const result=await pool.query('SELECT DISTINCT p.key FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=$1 ORDER BY p.key',[req.auth!.userId]); return {data:result.rows.map((row) => row.key)}; });
  app.post('/api/v1/admin/:entity/:id/archive', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; const allowed=hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']) || await hasPermission(req,'season.archive'); if(!allowed){await recordAccessDenied(req,'ARCHIVE_DENIED');return reply.code(403).send({error:'forbidden'});} const entity=z.enum(['organizations','educational_institutions','participants','results']).safeParse((request.params as {entity:string}).entity); const id=z.string().uuid().safeParse((request.params as {id:string}).id); if(!entity.success||!id.success)return reply.code(400).send({error:'validation_error'}); const table=entity.data; const result=await pool.query(`UPDATE ${table} SET status='ARCHIVED', archived_at=now(), updated_at=now() WHERE id=$1 AND archived_at IS NULL RETURNING id`,[id.data]); if(!result.rowCount)return reply.code(404).send({error:'not_found'}); await audit(req.auth!.userId,'ARCHIVE',table.toUpperCase(),id.data); return {success:true,id:id.data}; });
  app.post('/api/v1/admin/licenses/sync-expiry', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const result=await pool.query("UPDATE sports_licenses SET status='EXPIRED',updated_at=now() WHERE status='ACTIVE' AND expires_at IS NOT NULL AND expires_at <= now() AND archived_at IS NULL RETURNING id"); for(const row of result.rows) await audit(req.auth!.userId,'EXPIRE','LICENSE',row.id); return {updated:result.rowCount}; });
  app.get('/api/v1/admin/users', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const query=z.object({search:z.string().max(100).optional(),status:z.enum(['ACTIVE','SUSPENDED','DISABLED']).optional(),roleId:z.string().uuid().optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(50)}).parse(request.query); const values:any[]=[]; const where:string[]=[]; if(query.search){values.push(`%${query.search}%`);where.push(`(u.username ILIKE $${values.length} OR u.display_name ILIKE $${values.length} OR u.email ILIKE $${values.length})`)} if(query.status){values.push(query.status);where.push(`u.status=$${values.length}`)} if(query.roleId){values.push(query.roleId);where.push(`EXISTS (SELECT 1 FROM user_roles filter_ur WHERE filter_ur.user_id=u.id AND filter_ur.role_id=$${values.length})`)} const offset=(query.page-1)*query.pageSize; values.push(query.pageSize,offset); const result=await pool.query(`SELECT u.id,u.username,u.email,u.display_name,u.status,u.created_at,COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL),'{}') AS roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY u.id ORDER BY u.username LIMIT $${values.length-1} OFFSET $${values.length}`,values); return {data:result.rows,page:query.page,pageSize:query.pageSize}; });
  app.get('/api/v1/admin/roles', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const result=await pool.query('SELECT id,name,description FROM roles ORDER BY name'); return {data:result.rows}; });
  app.get('/api/v1/admin/permissions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const result=await pool.query('SELECT id,key,description FROM permissions ORDER BY key'); return {data:result.rows}; });
  app.get('/api/v1/admin/roles/:id/permissions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); if(!id.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query('SELECT p.id,p.key,p.description FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id WHERE rp.role_id=$1 ORDER BY p.key',[id.data]); return {data:result.rows}; });
  app.put('/api/v1/admin/roles/:id/permissions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({permissionIds:z.array(z.string().uuid()).max(100)}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const role=await pool.query('SELECT id FROM roles WHERE id=$1',[id.data]); if(!role.rowCount)return reply.code(404).send({error:'role_not_found'}); const permissions=await pool.query('SELECT id FROM permissions WHERE id=ANY($1::uuid[])',[parsed.data.permissionIds]); if(permissions.rowCount!==parsed.data.permissionIds.length)return reply.code(400).send({error:'permission_not_found'}); const client=await pool.connect(); try{await client.query('BEGIN'); await client.query('DELETE FROM role_permissions WHERE role_id=$1',[id.data]); for(const permissionId of parsed.data.permissionIds)await client.query('INSERT INTO role_permissions(role_id,permission_id) VALUES($1,$2)',[id.data,permissionId]); await client.query('COMMIT'); await audit(req.auth!.userId,'UPDATE_PERMISSIONS','ROLE',id.data,{permissionIds:parsed.data.permissionIds}); return {success:true};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release()} });
  app.put('/api/v1/admin/users/:id/roles', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const userId=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({roleIds:z.array(z.string().uuid()).max(20)}).safeParse(request.body); if(!userId.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const user=await pool.query('SELECT id FROM users WHERE id=$1',[userId.data]); if(!user.rowCount)return reply.code(404).send({error:'user_not_found'}); const roles=await pool.query('SELECT id FROM roles WHERE id=ANY($1::uuid[])',[parsed.data.roleIds]); if(roles.rowCount!==parsed.data.roleIds.length)return reply.code(400).send({error:'role_not_found'}); const client=await pool.connect(); try{await client.query('BEGIN'); await client.query('DELETE FROM user_roles WHERE user_id=$1',[userId.data]); for(const roleId of parsed.data.roleIds)await client.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2)',[userId.data,roleId]); await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()} await audit(req.auth!.userId,'UPDATE_ROLES','USER',userId.data,{roleIds:parsed.data.roleIds}); return {success:true}; });
  app.get('/api/v1/admin/lookups', async (request, reply) => { if(!requireAuth(request as AuthenticatedRequest,reply))return; const [seasons,competitions,participants,organizations]=await Promise.all([pool.query("SELECT id,name,status FROM seasons WHERE archived_at IS NULL ORDER BY start_date DESC"),pool.query("SELECT id,name,status,season_id FROM competitions WHERE archived_at IS NULL ORDER BY created_at DESC"),pool.query("SELECT id,given_name,family_name,institution_id FROM participants WHERE archived_at IS NULL ORDER BY created_at DESC"),pool.query("SELECT id,name,code FROM organizations WHERE archived_at IS NULL ORDER BY name")]); return {data:{seasons:seasons.rows,competitions:competitions.rows,participants:participants.rows,organizations:organizations.rows}}; });
  app.get('/api/v1/admin/audit', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const query=z.object({action:z.string().max(80).optional(),entityType:z.string().max(80).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(50)}).parse(request.query); const values:any[]=[]; const where:string[]=[]; if(query.action){values.push(query.action);where.push(`action=$${values.length}`)} if(query.entityType){values.push(query.entityType);where.push(`entity_type=$${values.length}`)} const offset=(query.page-1)*query.pageSize; values.push(query.pageSize,offset); const result=await pool.query(`SELECT id,occurred_at,actor_user_id,action,entity_type,entity_id,result_status,metadata FROM audit_logs ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY occurred_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values); return {data:result.rows,page:query.page,pageSize:query.pageSize}; });
  app.get('/api/v1/admin/audit/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); if(!id.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query('SELECT id,occurred_at,actor_user_id,action,entity_type,entity_id,result_status,metadata,request_id FROM audit_logs WHERE id=$1',[id.data]); if(!result.rowCount)return reply.code(404).send({error:'audit_not_found'}); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/audit.csv', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const query=z.object({action:z.string().max(80).optional(),entityType:z.string().max(80).optional()}).parse(request.query); const values:any[]=[]; const where:string[]=[]; if(query.action){values.push(query.action);where.push(`action=$${values.length}`)} if(query.entityType){values.push(query.entityType);where.push(`entity_type=$${values.length}`)} const result=await pool.query(`SELECT occurred_at,actor_user_id,action,entity_type,entity_id,result_status FROM audit_logs ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY occurred_at DESC LIMIT 10000`,values); const escape=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`; const csv=['occurred_at,actor_user_id,action,entity_type,entity_id,result_status',...result.rows.map((row)=>[row.occurred_at,row.actor_user_id,row.action,row.entity_type,row.entity_id,row.result_status].map(escape).join(','))].join('\n'); return reply.header('content-type','text/csv; charset=utf-8').header('content-disposition','attachment; filename="nssms-audit.csv"').send(csv); });
  app.get('/api/v1/admin/reports/summary', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const result=await pool.query(`SELECT (SELECT count(*) FROM organizations WHERE archived_at IS NULL)::int AS organizations,(SELECT count(*) FROM educational_institutions WHERE archived_at IS NULL)::int AS institutions,(SELECT count(*) FROM participants WHERE archived_at IS NULL)::int AS participants,(SELECT count(*) FROM seasons WHERE archived_at IS NULL)::int AS seasons,(SELECT count(*) FROM competitions WHERE archived_at IS NULL)::int AS competitions,(SELECT count(*) FROM sports_licenses WHERE archived_at IS NULL)::int AS licenses,(SELECT count(*) FROM audit_logs)::int AS audit_events`); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/reports/status-breakdown', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const [seasons,competitions,licenses]=await Promise.all([pool.query('SELECT status,count(*)::int AS count FROM seasons WHERE archived_at IS NULL GROUP BY status ORDER BY status'),pool.query('SELECT status,count(*)::int AS count FROM competitions WHERE archived_at IS NULL GROUP BY status ORDER BY status'),pool.query('SELECT status,count(*)::int AS count FROM sports_licenses WHERE archived_at IS NULL GROUP BY status ORDER BY status')]); return {data:{seasons:seasons.rows,competitions:competitions.rows,licenses:licenses.rows}}; });
  app.get('/api/v1/admin/seasons', async (request, reply) => { if (!requireAuth(request as AuthenticatedRequest, reply)) return; const query=z.object({search:z.string().max(100).optional(),status:z.enum(['DRAFT','UNDER_REVIEW','APPROVED','ACTIVE','CLOSED','ARCHIVED']).optional()}).parse(request.query); const values:any[]=[]; const where=['archived_at IS NULL']; if(query.search){values.push(`%${query.search}%`);where.push(`name ILIKE $${values.length}`)} if(query.status){values.push(query.status);where.push(`status=$${values.length}`)} const result = await pool.query(`SELECT id,name,start_date,end_date,status,created_at,updated_at FROM seasons WHERE ${where.join(' AND ')} ORDER BY start_date DESC`,values); return { data: result.rows }; });
  app.post('/api/v1/admin/seasons', async (request, reply) => { const req = request as AuthenticatedRequest; if (!requireAuth(req, reply)) return; if (!hasRole(req, ['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR'])) return reply.code(403).send({ error:'forbidden' }); const parsed = seasonInput.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error:'validation_error', details: parsed.error.flatten() }); const result = await pool.query('INSERT INTO seasons (name,start_date,end_date) VALUES ($1,$2,$3) RETURNING *', [parsed.data.name, parsed.data.startDate, parsed.data.endDate]); await audit(req.auth!.userId,'CREATE','SEASON',result.rows[0].id); return reply.code(201).send({ data: result.rows[0] }); });
  app.post('/api/v1/admin/seasons/:id/transition', async (request, reply) => { const req = request as AuthenticatedRequest; if (!requireAuth(req, reply)) return; if (!hasRole(req, ['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR'])) return reply.code(403).send({ error:'forbidden' }); const parsed = z.object({ to: z.string() }).safeParse(request.body); const id = z.string().uuid().safeParse((request.params as {id:string}).id); if (!parsed.success || !id.success) return reply.code(400).send({ error:'validation_error' }); const current = await pool.query('SELECT status FROM seasons WHERE id=$1 AND archived_at IS NULL',[id.data]); if (!current.rowCount) return reply.code(404).send({ error:'not_found' }); try { assertTransition('season', current.rows[0].status, parsed.data.to); } catch { return reply.code(409).send({ error:'invalid_transition' }); } const updated = await pool.query('UPDATE seasons SET status=$1::season_status,updated_at=now(),archived_at=CASE WHEN $1::text=\'ARCHIVED\' THEN now() ELSE archived_at END WHERE id=$2 RETURNING *',[parsed.data.to,id.data]); await audit(req.auth!.userId,'TRANSITION','SEASON',id.data,{from:current.rows[0].status,to:parsed.data.to}); return { data: updated.rows[0] }; });
  app.patch('/api/v1/admin/seasons/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({name:z.string().min(2).max(200).optional(),startDate:z.coerce.date().optional(),endDate:z.coerce.date().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const current=await pool.query("SELECT status FROM seasons WHERE id=$1 AND archived_at IS NULL",[id.data]); if(!current.rowCount)return reply.code(404).send({error:'season_not_found'}); if(current.rows[0].status!=='DRAFT')return reply.code(409).send({error:'only_draft_seasons_are_editable'}); const result=await pool.query('UPDATE seasons SET name=COALESCE($1,name),start_date=COALESCE($2,start_date),end_date=COALESCE($3,end_date) WHERE id=$4 RETURNING *',[parsed.data.name??null,parsed.data.startDate??null,parsed.data.endDate??null,id.data]); await audit(req.auth!.userId,'UPDATE','SEASON',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/organizations', async (request, reply) => { if (!requireAuth(request as AuthenticatedRequest, reply)) return; const result = await pool.query('SELECT * FROM organizations WHERE archived_at IS NULL ORDER BY name'); return { data: result.rows }; });
  app.post('/api/v1/admin/organizations', async (request, reply) => { const req=request as AuthenticatedRequest; if (!requireAuth(req,reply)) return; if (!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR'])) return reply.code(403).send({error:'forbidden'}); const parsed=organizationInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error'}); try { const result=await pool.query('INSERT INTO organizations(name,code) VALUES($1,$2) RETURNING *',[parsed.data.name,parsed.data.code??null]); await audit(req.auth!.userId,'CREATE','ORGANIZATION',result.rows[0].id); return reply.code(201).send({data:result.rows[0]}); } catch(error) { if((error as {code?:string}).code==='23505')return reply.code(409).send({error:'organization_code_exists'}); throw error; } });
  app.post('/api/v1/admin/organizations/:id/status', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({status:z.enum(['ACTIVE','INACTIVE','ARCHIVED'])}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE organizations SET status=$1::record_status,archived_at=CASE WHEN $1::text='ARCHIVED' THEN now() ELSE archived_at END,updated_at=now() WHERE id=$2 AND archived_at IS NULL RETURNING id,status",[parsed.data.status,id.data]); if(!result.rowCount)return reply.code(404).send({error:'organization_not_found'}); await audit(req.auth!.userId,'UPDATE_STATUS','ORGANIZATION',id.data,{status:parsed.data.status}); return {data:result.rows[0]}; });
  app.patch('/api/v1/admin/organizations/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=organizationInput.partial().safeParse(request.body); if(!id.success||!parsed.success||Object.keys(parsed.data).length===0)return reply.code(400).send({error:'validation_error'}); const result=await pool.query('UPDATE organizations SET name=COALESCE($1,name),code=COALESCE($2,code) WHERE id=$3 AND archived_at IS NULL RETURNING *',[parsed.data.name??null,parsed.data.code??null,id.data]); if(!result.rowCount)return reply.code(404).send({error:'organization_not_found'}); await audit(req.auth!.userId,'UPDATE','ORGANIZATION',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/institutions', async (request, reply) => { if(!requireAuth(request as AuthenticatedRequest,reply))return; const query=z.object({search:z.string().max(100).optional(),organizationId:z.string().uuid().optional()}).parse(request.query); const values:any[]=[]; const where=['i.archived_at IS NULL']; if(query.search){values.push(`%${query.search}%`);where.push(`(i.name ILIKE $${values.length} OR i.code ILIKE $${values.length})`)} if(query.organizationId){values.push(query.organizationId);where.push(`i.organization_id=$${values.length}`)} const result=await pool.query(`SELECT i.*,o.name AS organization_name FROM educational_institutions i JOIN organizations o ON o.id=i.organization_id WHERE ${where.join(' AND ')} ORDER BY i.name`,values); return {data:result.rows}; });
  app.post('/api/v1/admin/institutions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const parsed=z.object({organizationId:z.string().uuid(),name:z.string().min(2).max(200),code:z.string().max(50).optional()}).safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error'}); const org=await pool.query('SELECT id FROM organizations WHERE id=$1 AND archived_at IS NULL',[parsed.data.organizationId]); if(!org.rowCount)return reply.code(404).send({error:'organization_not_found'}); try { const result=await pool.query('INSERT INTO educational_institutions(organization_id,name,code) VALUES($1,$2,$3) RETURNING *',[parsed.data.organizationId,parsed.data.name,parsed.data.code??null]); await audit(req.auth!.userId,'CREATE','EDUCATIONAL_INSTITUTION',result.rows[0].id); return reply.code(201).send({data:result.rows[0]}); } catch(error) { if((error as {code?:string}).code==='23505')return reply.code(409).send({error:'institution_code_exists'}); throw error; } });
  app.post('/api/v1/admin/institutions/:id/status', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({status:z.enum(['ACTIVE','INACTIVE','ARCHIVED'])}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE educational_institutions SET status=$1::record_status,archived_at=CASE WHEN $1::text='ARCHIVED' THEN now() ELSE archived_at END,updated_at=now() WHERE id=$2 AND archived_at IS NULL RETURNING id,status",[parsed.data.status,id.data]); if(!result.rowCount)return reply.code(404).send({error:'institution_not_found'}); await audit(req.auth!.userId,'UPDATE_STATUS','EDUCATIONAL_INSTITUTION',id.data,{status:parsed.data.status}); return {data:result.rows[0]}; });
  app.patch('/api/v1/admin/institutions/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({name:z.string().min(2).max(200).optional(),code:z.string().max(50).optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query('UPDATE educational_institutions SET name=COALESCE($1,name),code=COALESCE($2,code) WHERE id=$3 AND archived_at IS NULL RETURNING *',[parsed.data.name??null,parsed.data.code??null,id.data]); if(!result.rowCount)return reply.code(404).send({error:'institution_not_found'}); await audit(req.auth!.userId,'UPDATE','EDUCATIONAL_INSTITUTION',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/participants', async (request, reply) => { if (!requireAuth(request as AuthenticatedRequest, reply)) return; const query=z.object({search:z.string().max(100).optional(),institutionId:z.string().uuid().optional(),status:z.enum(['ACTIVE','INACTIVE','ARCHIVED']).optional()}).parse(request.query); const values:any[]=[]; const where=['p.archived_at IS NULL']; if(query.search){values.push(`%${query.search}%`);where.push(`(p.given_name ILIKE $${values.length} OR p.family_name ILIKE $${values.length})`)} if(query.institutionId){values.push(query.institutionId);where.push(`p.institution_id=$${values.length}`)} if(query.status){values.push(query.status);where.push(`p.status=$${values.length}`)} const result=await pool.query(`SELECT p.*,i.name AS institution_name FROM participants p JOIN educational_institutions i ON i.id=p.institution_id WHERE ${where.join(' AND ')} ORDER BY p.created_at DESC`,values); return {data:result.rows}; });
  app.post('/api/v1/admin/participants', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR','ASSOCIATION_ADMINISTRATOR','MEMBER_INSTITUTION_USER']))return reply.code(403).send({error:'forbidden'}); const parsed=participantInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error',details:parsed.error.flatten()}); const result=await pool.query('INSERT INTO participants(institution_id,given_name,family_name,date_of_birth) VALUES($1,$2,$3,$4) RETURNING *',[parsed.data.institutionId,parsed.data.givenName,parsed.data.familyName,parsed.data.dateOfBirth??null]); await audit(req.auth!.userId,'CREATE','PARTICIPANT',result.rows[0].id); return reply.code(201).send({data:result.rows[0]}); });
  app.post('/api/v1/admin/participants/:id/status', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({status:z.enum(['ACTIVE','INACTIVE','ARCHIVED'])}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE participants SET status=$1::record_status,archived_at=CASE WHEN $1::text='ARCHIVED' THEN now() ELSE archived_at END,updated_at=now() WHERE id=$2 AND archived_at IS NULL RETURNING id,status",[parsed.data.status,id.data]); if(!result.rowCount)return reply.code(404).send({error:'participant_not_found'}); await audit(req.auth!.userId,'UPDATE_STATUS','PARTICIPANT',id.data,{status:parsed.data.status}); return {data:result.rows[0]}; });
  app.patch('/api/v1/admin/participants/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({institutionId:z.string().uuid().optional(),givenName:z.string().min(1).max(100).optional(),familyName:z.string().min(1).max(100).optional(),dateOfBirth:z.coerce.date().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); if(parsed.data.institutionId){const institution=await pool.query('SELECT id FROM educational_institutions WHERE id=$1 AND archived_at IS NULL',[parsed.data.institutionId]);if(!institution.rowCount)return reply.code(400).send({error:'institution_not_found'});} const result=await pool.query('UPDATE participants SET institution_id=COALESCE($1,institution_id),given_name=COALESCE($2,given_name),family_name=COALESCE($3,family_name),date_of_birth=COALESCE($4,date_of_birth) WHERE id=$5 AND archived_at IS NULL RETURNING *',[parsed.data.institutionId??null,parsed.data.givenName??null,parsed.data.familyName??null,parsed.data.dateOfBirth??null,id.data]); if(!result.rowCount)return reply.code(404).send({error:'participant_not_found'}); await audit(req.auth!.userId,'UPDATE','PARTICIPANT',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/competitions', async (request, reply) => { if (!requireAuth(request as AuthenticatedRequest, reply)) return; const query=z.object({search:z.string().max(100).optional(),seasonId:z.string().uuid().optional(),status:z.enum(['DRAFT','REVIEW','APPROVED','REGISTRATION','ACTIVE','RESULTS','CLOSED','ARCHIVED']).optional()}).parse(request.query); const values:any[]=[]; const where=['c.archived_at IS NULL']; if(query.search){values.push(`%${query.search}%`);where.push(`c.name ILIKE $${values.length}`)} if(query.seasonId){values.push(query.seasonId);where.push(`c.season_id=$${values.length}`)} if(query.status){values.push(query.status);where.push(`c.status=$${values.length}`)} const result=await pool.query(`SELECT c.*,s.name AS season_name FROM competitions c JOIN seasons s ON s.id=c.season_id WHERE ${where.join(' AND ')} ORDER BY c.created_at DESC`,values); return {data:result.rows}; });
  app.post('/api/v1/admin/competitions', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const parsed=competitionInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error'}); const season=await pool.query('SELECT id FROM seasons WHERE id=$1 AND archived_at IS NULL',[parsed.data.seasonId]); if(!season.rowCount)return reply.code(400).send({error:'season_not_found'}); const result=await pool.query('INSERT INTO competitions(season_id,name,start_date,end_date) VALUES($1,$2,$3,$4) RETURNING *',[parsed.data.seasonId,parsed.data.name,parsed.data.startDate??null,parsed.data.endDate??null]); await audit(req.auth!.userId,'CREATE','COMPETITION',result.rows[0].id); return reply.code(201).send({data:result.rows[0]}); });
  app.post('/api/v1/admin/competitions/:id/transition', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({to:z.string()}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const current=await pool.query('SELECT status FROM competitions WHERE id=$1 AND archived_at IS NULL',[id.data]); if(!current.rowCount)return reply.code(404).send({error:'not_found'}); try{assertTransition('competition',current.rows[0].status,parsed.data.to)}catch{return reply.code(409).send({error:'invalid_transition'})} const updated=await pool.query('UPDATE competitions SET status=$1::competition_status,updated_at=now(),archived_at=CASE WHEN $1::text=\'ARCHIVED\' THEN now() ELSE archived_at END WHERE id=$2 RETURNING *',[parsed.data.to,id.data]); await audit(req.auth!.userId,'TRANSITION','COMPETITION',id.data,{from:current.rows[0].status,to:parsed.data.to}); return {data:updated.rows[0]}; });
  app.patch('/api/v1/admin/competitions/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({name:z.string().min(2).max(200).optional(),startDate:z.coerce.date().optional(),endDate:z.coerce.date().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const current=await pool.query("SELECT status FROM competitions WHERE id=$1 AND archived_at IS NULL",[id.data]); if(!current.rowCount)return reply.code(404).send({error:'competition_not_found'}); if(!['DRAFT','REVIEW'].includes(current.rows[0].status))return reply.code(409).send({error:'competition_not_editable'}); const result=await pool.query('UPDATE competitions SET name=COALESCE($1,name),start_date=COALESCE($2,start_date),end_date=COALESCE($3,end_date) WHERE id=$4 RETURNING *',[parsed.data.name??null,parsed.data.startDate??null,parsed.data.endDate??null,id.data]); await audit(req.auth!.userId,'UPDATE','COMPETITION',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/licenses', async (request, reply) => { if(!requireAuth(request as AuthenticatedRequest,reply))return; const query=z.object({participantId:z.string().uuid().optional(),status:z.enum(['APPLICATION','VALIDATION','APPROVAL','ISSUED','ACTIVE','EXPIRED','SUSPENDED','ARCHIVED']).optional()}).parse(request.query); const values:any[]=[]; const where=['l.archived_at IS NULL']; if(query.participantId){values.push(query.participantId);where.push(`l.participant_id=$${values.length}`)} if(query.status){values.push(query.status);where.push(`l.status=$${values.length}`)} const result=await pool.query(`SELECT l.id,l.participant_id,l.status,l.issued_at,l.expires_at,l.created_at,l.license_kind,l.discipline,l.sport_kind,l.age_category,l.gender_category,p.given_name,p.family_name FROM sports_licenses l JOIN participants p ON p.id=l.participant_id WHERE ${where.join(' AND ')} ORDER BY l.created_at DESC`,values); return {data:result.rows}; });
  app.post('/api/v1/admin/licenses', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR','ASSOCIATION_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const parsed=licenseInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'validation_error'}); const participant=await pool.query('SELECT id FROM participants WHERE id=$1 AND archived_at IS NULL',[parsed.data.participantId]); if(!participant.rowCount)return reply.code(400).send({error:'participant_not_found'}); const license=await pool.query('INSERT INTO sports_licenses(participant_id,status,issued_at,expires_at,license_kind,discipline,sport_kind,age_category,gender_category) VALUES($1,\'ACTIVE\',now(),$2,$3,$4,$5,$6,$7) RETURNING *',[parsed.data.participantId,parsed.data.expiresAt??null,parsed.data.licenseKind??'STUDENT',parsed.data.discipline??null,parsed.data.sportKind??null,parsed.data.ageCategory??null,parsed.data.genderCategory??null]); const reference=createVerificationReference(); await pool.query('INSERT INTO qr_verifications(license_id,reference_hash) VALUES($1,$2)',[license.rows[0].id,hashVerificationReference(reference)]); await audit(req.auth!.userId,'ISSUE','LICENSE',license.rows[0].id); return reply.code(201).send({data:license.rows[0],verificationReference:reference}); });
  app.post('/api/v1/admin/licenses/:id/transition', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({to:z.string()}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const current=await pool.query('SELECT status FROM sports_licenses WHERE id=$1 AND archived_at IS NULL',[id.data]); if(!current.rowCount)return reply.code(404).send({error:'not_found'}); try{assertTransition('license',current.rows[0].status,parsed.data.to)}catch{return reply.code(409).send({error:'invalid_transition'})} const updated=await pool.query('UPDATE sports_licenses SET status=$1::license_status,updated_at=now(),archived_at=CASE WHEN $1::text=\'ARCHIVED\' THEN now() ELSE archived_at END WHERE id=$2 RETURNING *',[parsed.data.to,id.data]); await audit(req.auth!.userId,'TRANSITION','LICENSE',id.data,{from:current.rows[0].status,to:parsed.data.to}); return {data:updated.rows[0]}; });
  app.patch('/api/v1/admin/licenses/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({expiresAt:z.coerce.date().nullable().optional()}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE sports_licenses SET expires_at=$1 WHERE id=$2 AND archived_at IS NULL AND status IN ('APPLICATION','VALIDATION','APPROVAL','ISSUED','ACTIVE') RETURNING *",[parsed.data.expiresAt??null,id.data]); if(!result.rowCount)return reply.code(404).send({error:'license_not_editable'}); await audit(req.auth!.userId,'UPDATE','LICENSE',id.data); return {data:result.rows[0]}; });
  app.get('/api/v1/admin/results', async (request, reply) => { if(!requireAuth(request as AuthenticatedRequest,reply))return; const query=z.object({competitionId:z.string().uuid().optional(),participantId:z.string().uuid().optional()}).parse(request.query); const values:any[]=[]; const where=['r.archived_at IS NULL']; if(query.competitionId){values.push(query.competitionId);where.push(`r.competition_id=$${values.length}`)} if(query.participantId){values.push(query.participantId);where.push(`r.participant_id=$${values.length}`)} const result=await pool.query(`SELECT r.*,c.name AS competition_name FROM results r JOIN competitions c ON c.id=r.competition_id WHERE ${where.join(' AND ')} ORDER BY r.created_at DESC`,values); return {data:result.rows}; });
  app.post('/api/v1/admin/competitions/:id/results', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const competitionId=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=resultInput.safeParse(request.body); if(!competitionId.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const competition=await pool.query("SELECT id,status FROM competitions WHERE id=$1 AND archived_at IS NULL",[competitionId.data]); if(!competition.rowCount)return reply.code(404).send({error:'competition_not_found'}); if(!['ACTIVE','RESULTS'].includes(competition.rows[0].status))return reply.code(409).send({error:'competition_not_ready_for_results'}); if(parsed.data.participantId){const participant=await pool.query('SELECT id FROM participants WHERE id=$1 AND archived_at IS NULL',[parsed.data.participantId]);if(!participant.rowCount)return reply.code(400).send({error:'participant_not_found'});} const result=await pool.query('INSERT INTO results(competition_id,participant_id,result_data) VALUES($1,$2,$3) RETURNING *',[competitionId.data,parsed.data.participantId??null,parsed.data.resultData]); await audit(req.auth!.userId,'CREATE','RESULT',result.rows[0].id); return reply.code(201).send({data:result.rows[0]}); });
  app.patch('/api/v1/admin/results/:id', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({resultData:z.record(z.unknown())}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE results r SET result_data=$1,updated_at=now() FROM competitions c WHERE r.id=$2 AND r.competition_id=c.id AND c.status IN ('ACTIVE','RESULTS') AND r.archived_at IS NULL RETURNING r.*",[parsed.data.resultData,id.data]); if(!result.rowCount)return reply.code(404).send({error:'result_not_editable'}); await audit(req.auth!.userId,'UPDATE','RESULT',id.data); return {data:result.rows[0]}; });
  app.post('/api/v1/admin/results/:id/status', async (request, reply) => { const req=request as AuthenticatedRequest; if(!requireAuth(req,reply))return; if(!hasRole(req,['SYSTEM_ADMINISTRATOR','NATIONAL_ADMINISTRATOR']))return reply.code(403).send({error:'forbidden'}); const id=z.string().uuid().safeParse((request.params as {id:string}).id); const parsed=z.object({status:z.enum(['ACTIVE','INACTIVE','ARCHIVED'])}).safeParse(request.body); if(!id.success||!parsed.success)return reply.code(400).send({error:'validation_error'}); const result=await pool.query("UPDATE results SET status=$1::record_status,archived_at=CASE WHEN $1::text='ARCHIVED' THEN now() ELSE archived_at END,updated_at=now() WHERE id=$2 AND archived_at IS NULL RETURNING id,status",[parsed.data.status,id.data]); if(!result.rowCount)return reply.code(404).send({error:'result_not_found'}); await audit(req.auth!.userId,'UPDATE_STATUS','RESULT',id.data,{status:parsed.data.status}); return {data:result.rows[0]}; });
}
